name: GitHub Action CI
on: [push]
jobs:
  build-and-delpoy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello GitHub Actions"

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "13.14.0"

      - name: install and build
        run: |
          node -v
          npm ci
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
